USE ${DATABASE};

LOAD DATA INPATH '${HDFS_BASE_DIR}/landing_zone/countycases.csv' OVERWRITE INTO TABLE COUNTY_CASES_SWEEP;
LOAD DATA INPATH '${HDFS_BASE_DIR}/landing_zone/deaths.csv' OVERWRITE INTO TABLE DEATHS_SWEEP;
LOAD DATA INPATH '${HDFS_BASE_DIR}/landing_zone/demographics.csv' OVERWRITE INTO TABLE DEMOGRAPHICS_SWEEP;

INSERT INTO TABLE COUNTY_CASES_ARCHIVE
SELECT
    CCS.*,
    '${PROCESSING_CYCLE}',
    '${ARCHIVE_PARTITION}'
FROM
COUNTY_CASES_SWEEP CCS;

INSERT OVERWRITE TABLE COUNTY_CASES
SELECT
    CCS.*
FROM
    COUNTY_CASES_SWEEP CCS;

INSERT INTO TABLE DEATHS_ARCHIVE
SELECT
    D.*,
    '${PROCESSING_CYCLE}',
    '${ARCHIVE_PARTITION}'
FROM
    DEATHS_SWEEP D;

INSERT OVERWRITE TABLE DEATHS
SELECT
    D.*
FROM
    DEATHS_SWEEP D;

INSERT INTO TABLE DEMOGRAPHICS_ARCHIVE
SELECT
    D.*,
    '${PROCESSING_CYCLE}',
    '${ARCHIVE_PARTITION}'
FROM
    DEMOGRAPHICS_SWEEP D;

INSERT OVERWRITE TABLE DEMOGRAPHICS
SELECT
    D.*
FROM
    DEMOGRAPHICS_SWEEP D;

