#######################################################
# Requires the Ranger Hive/HDFS Best Practive Policies.
#######################################################

- hosts: sdlc
  become: true
  become_user: '{{ tpcds_user }}'

  vars:
    hive_testbench: https://github.com/hortonworks/hive-testbench.git

  tasks:
    - name: Create Hive TPCPS Local Directory
      file:
        path: /home/{{ tpcds_user }}/hive-testbench
        state: directory
        owner: '{{ tpcds_user }}'
        mode: 0744
    - name: Clone TPCDS (Hive-testbench)
      git:
        repo: https://github.com/hortonworks/hive-testbench.git
        dest: /home/{{ tpcds_user }}/hive-testbench

    - name:                    TPCDS Database Access for {{ tpcds_user }}
      uri:
        url:                   '{{ ranger_url_base }}/service/public/v2/api/policy'
        body_format:           json
        body:
          '{
            "isEnabled":       true,
            "service":         "{{ cluster_name }}_hive",
            "name":            "TPCDS - Databases",
            "description":     "TPCDS User Database Access",
            "isAuditEnabled":  true,
            "resources":       {
              "database":      {
                "values":      ["tpcds*"],
                "isExcludes":  false,
                "isRecursive": false
              },
              "column":        {
                "values":      ["*"],
                "isExcludes":  false,
                "isRecursive": false
              },
              "table":         {
                "values":      ["*"],
                "isExcludes":  false,
                "isRecursive": false
              }
            },
            "policyItems":     [{
              "accesses":      [{
                "type":        "select",
                "isAllowed":   true
              }, {
                "type":        "update",
                "isAllowed":   true
              }, {
                "type":        "create",
                "isAllowed":   true
              }, {
                "type":        "drop",
                "isAllowed":   true
              }, {
                "type":        "alter",
                "isAllowed":   true
              }, {
                "type":        "index",
                "isAllowed":   true
              }, {
                "type":        "lock",
                "isAllowed":   true
              }, {
                "type":        "all",
                "isAllowed":   true
              }, {
                "type":        "read",
                "isAllowed":   true
              }, {
                "type":        "write",
                "isAllowed":   true
              }, {
                "type":        "repladmin",
                "isAllowed":   true
              }, {
                "type":        "serviceadmin",
                "isAllowed":   true
              }],
              "users":         ["{{ tpcds_user }}"],
              "groups":        [],
              "conditions":    [],
              "delegateAdmin": false
            }]
          }'
        method:                POST
        user:                  '{{ ranger_admin_user }}'
        password:              '{{ ranger_admin_ldap_password }}'
        force_basic_auth:      yes
        status_code:           200,400
        headers:
          Content-Type:        "application/json; charset=utf8"
          X-XSRF-HEADER:       "valid"
          User-Agent:          "Ansible HDP Best Practices"
      tags:
        - ranger

    - name: Build TPCDS
      shell: cd /home/{{ tpcds_user }}/hive-testbench; ./tpcds-build.sh
      tags:
        - build
    - name: Create TPCDS Dataset and Build Hive Tables
      shell: cd /home/{{ tpcds_user }}/hive-testbench; ./tpcds-setup.sh {{ tpcds_size }}
      tags:
        - build
        - gen
    # - name: Run Analyze on built tables.
