USE ${database};

-- Create Tables
DROP TABLE CC_TRANS_ALT_FROM_STREAMING;

CREATE TABLE
  IF NOT EXISTS CC_TRANS_ALT_FROM_STREAMING
(
  CC_TRANS STRING   ,
  CCN STRING        ,
  TRANS_TS BIGINT,
  ST STRING      ,
  AMNT DOUBLE
)
  PARTITIONED BY
(
  PROCESSING_CYCLE STRING
);

DROP TABLE CC_TRANS_ALT_FROM_STREAMING_EXT;

CREATE EXTERNAL TABLE
  IF NOT EXISTS CC_TRANS_ALT_FROM_STREAMING_EXT
(
  CC_TRANS STRING   ,
  CCN STRING        ,
  TRANS_TS BIGINT,
  ST STRING      ,
  AMNT DOUBLE
)
  PARTITIONED BY
(
  PROCESSING_CYCLE STRING
)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION
  '${external_location}';
;
