USE ${TARGET_DB};

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CUSTOMER_SRC;
DROP TABLE IF EXISTS VISIT;
DROP TABLE IF EXISTS VISIT_SRC;
DROP TABLE IF EXISTS PURCHASE;
DROP TABLE IF EXISTS PURCHASE_SRC;
