CREATE DATABASE IF NOT EXISTS ${TARGET_DB};

USE ${TARGET_DB};

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID          STRING,
    FULL_NAME   STRING,
    ADDRESS     STRING,
    STATE       STRING,
    CONTACT_NUM STRING
)
    STORED AS ORC;

DROP TABLE IF EXISTS VISIT;
CREATE TABLE IF NOT EXISTS VISIT
(
    ID          STRING,
    CUSTOMER_ID STRING,
    VISIT_TS    TIMESTAMP,
    STAY_TIME   BIGINT
) PARTITIONED BY (VISIT_DATE DATE)
    STORED AS ORC;

DROP TABLE IF EXISTS PURCHASE;
CREATE TABLE IF NOT EXISTS PURCHASE
(
    ID             STRING,
    CUSTOMER_ID    STRING,
    VISIT_ID       STRING,
    SALES_REP      STRING,
    REGISTER       STRING,
    TRANSACTION_ID STRING,
    DISCOUNT       DOUBLE,
    DISCOUNT_CODE  STRING,
    TOTAL_PURCHASE DOUBLE,
    TENDER_TYPE    STRING,
    PURCHASE_TS    TIMESTAMP
) PARTITIONED BY (PURCHASE_DATE DATE)
    STORED AS ORC;
