CREATE DATABASE IF NOT EXISTS ${SRC_DB};

USE ${SRC_DB};

DROP TABLE IF EXISTS CUSTOMER_SRC;
CREATE EXTERNAL TABLE IF NOT EXISTS CUSTOMER_SRC
(
    ID          STRING,
    FULL_NAME   STRING,
    ADDRESS     STRING,
    STATE       STRING,
    CONTACT_NUM STRING
) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY '\t'
LOCATION '/warehouse/tablespace/external/hive/retail.db/customer_src';

DROP TABLE IF EXISTS VISIT_SRC;
CREATE EXTERNAL TABLE IF NOT EXISTS VISIT_SRC
(
    ID          STRING,
    CUSTOMER_ID STRING,
    VISIT_TS    TIMESTAMP,
    STAY_TIME   BIGINT
) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY '\t'
LOCATION '/warehouse/tablespace/external/hive/retail.db/visit_src';

DROP TABLE IF EXISTS PURCHASE_SRC;
CREATE EXTERNAL TABLE IF NOT EXISTS PURCHASE_SRC
(
    ID             STRING,
    CUSTOMER_ID    STRING,
    VISIT_ID       STRING,
    SALES_REP      STRING,
    REGISTER       STRING,
    TRANSACTION_ID STRING,
    DISCOUNT       DOUBLE,
    DISCOUNT_CODE  STRING,
    TOTAL_PURCHASE DOUBLE,
    TENDER_TYPE    STRING
) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY '\t'
LOCATION '/warehouse/tablespace/external/hive/retail.db/purchase_src';

