USE COVID_GA;

SHOW TABLES;

SELECT *
FROM
    DEATHS;

SELECT *
FROM
    COUNTY_CASES;


SELECT
    COUNTY,
    RACE,
    SEX,
    COUNT(1) AS COUNT,
    AVG(AGE) AS AVERAGE_AGE
FROM
    DEATHS
WHERE
    COUNTY = 'Cobb'
GROUP BY
    COUNTY, RACE, SEX;



SELECT
    D.COUNTY,
    D.SEX,
    D.RACE,
    D.CHRONIC_CONDITION,
    COUNT(1)   AS COUNT,
    AVG(D.AGE) AS AVERAGE_AGE,
    CC.POSITIVE,
    CC.DEATHS,
    CC.HOSPITALIZATION
FROM
    DEATHS D
        INNER JOIN COUNTY_CASES CC ON D.COUNTY = CC.COUNTY_RESIDENT
-- WHERE D.COUNTY = 'Cobb'
GROUP BY
    D.COUNTY,
    D.RACE,
    D.SEX,
    D.CHRONIC_CONDITION,
    CC.POSITIVE, CC.DEATHS, CC.HOSPITALIZATION
ORDER BY
    D.COUNTY,
    D.SEX, D.RACE, D.CHRONIC_CONDITION;



SELECT
--     D.COUNTY,
--D.RACE,
D.SEX,
COUNT(1)   AS COUNT,
AVG(D.AGE) AS AVERAGE_AGE
--     CC.POSITIVE,
--     CC.DEATHS,
--     CC.HOSPITALIZATION
FROM
    DEATHS D
-- WHERE D.COUNTY = 'Cobb'
GROUP BY
--     D.COUNTY,
--     D.RACE,
D.SEX;
-- , CC.POSITIVE, CC.DEATHS, CC.HOSPITALIZATION;

SELECT * FROM DEMOGRAPHICS;