USE ${DATABASE};

SELECT COUNT(*) FROM COUNTY_CASES;
SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM COUNTY_CASES_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;
SELECT COUNT(*) FROM COUNTY_CASES_SWEEP;

SELECT COUNT(*) FROM DEATHS;
SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM DEATHS_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;
SELECT COUNT(*) FROM DEATHS_SWEEP;


SELECT COUNT(*) FROM DEMOGRAPHICS;
SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM DEMOGRAPHICS_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;
SELECT COUNT(*) FROM DEMOGRAPHICS_SWEEP;
