USE ${DATABASE};

SELECT COUNT(*) FROM COUNTRIES_AGGREGATED;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM COUNTRIES_AGGREGATED_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM COUNTRIES_AGGREGATED_SWEEP;

SELECT COUNT(*) FROM KEY_COUNTRIES_PIVOTED;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM KEY_COUNTRIES_PIVOTED_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM KEY_COUNTRIES_PIVOTED_SWEEP;

SELECT COUNT(*) FROM REFERENCE;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM REFERENCE_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM REFERENCE_SWEEP;

SELECT COUNT(*) FROM TIME_SERIES_COMBINED;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM TIME_SERIES_COMBINED_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM TIME_SERIES_COMBINED_SWEEP;

SELECT COUNT(*) FROM US_CONFIRMED;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM US_CONFIRMED_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM US_CONFIRMED_SWEEP;

SELECT COUNT(*) FROM US_DEATHS;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM US_DEATHS_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM US_DEATHS_SWEEP;

SELECT COUNT(*) FROM WORLDWIDE_AGGREGATED;

SELECT YEAR_MONTH, PROCESSING_CYCLE, COUNT(*) FROM WORLDWIDE_AGGREGATED_ARCHIVE GROUP BY YEAR_MONTH, PROCESSING_CYCLE;

SELECT COUNT(*) FROM WORLDWIDE_AGGREGATED_SWEEP;


