CREATE DATABASE IF NOT EXIST ${database};

USE ${database};

CREATE TABLE SLOWLY_CHANGING_FACT (
ID STRING,
IP_ADDR STRING,
SOURCE STRING,
FIELD_1 STRING,
FIELD_2 STRING,
AMOUNT_1 DOUBLE,
AMOUNT_2 DOUBLE,
UPDATE_TS TIMESTAMP
);

CREATE TABLE SLOWLY_CHANGING_FACT_DELTA (
ID STRING,
IP_ADDR STRING,
SOURCE STRING,
FIELD_1 STRING,
FIELD_2 STRING,
AMOUNT_1 DOUBLE,
AMOUNT_2 DOUBLE,
UPDATE_TS TIMESTAMP
)
PARTITIONED BY (INGEST_CYCLE BIGINT);

CREATE EXTERNAL TABLE SLOWLY_CHANGING_FACT_DELTA_ALT (
ID STRING,
IP_ADDR STRING,
SOURCE STRING,
FIELD_1 STRING,
AMOUNT_1 DOUBLE,
UPDATE_TS TIMESTAMP
)
PARTITIONED BY (processed_dt STRING)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE
  LOCATION '/user/nifi/datasets/external/slowly_changing_fact_delta_alt';

