- hosts:                     sdlc

  vars:
    hs2_jdbc_url:            jdbc:hive2://{{ zookeeper_server }}:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2

  tasks:
    - name:                  Create User Home Directories on local filesystem
      file:
        path:                /home/{{ user }}
        state:               directory
        mode:                0750
        owner:               '{{ user }}'
      become:                true
      tags:
        - local
        - ldap
        - hdp
    - name:                  Create User Home Directories in hdfs
      shell:                 hdfs dfs -mkdir -p /user/{{ user }};hdfs dfs -chown -R {{ user }}:hadoop /user/{{ user }}
      become:                true
      become_user:           hdfs
      tags:
        - local
        - ldap
        - hdp
    - name:                  Create Private User Database
      shell:                 /usr/hdp/current/hive-client/bin/beeline -u '{{ hs2_jdbc_url }}' -n '{{ hive_superuser }}' -p '{{ hive_superuser_password }}' -e "create database if not exists priv_{{ user }}"
      become:                true
      become_user:           hive
      tags:
        - local
        - ldap
        - hdp
