- hosts: hdp
  become: true

  tasks:
    - name: Create user on systems (local accounts)
      user:
        name: '{{ user }}'
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        groups: hadoop
      tags:
        - local
- hosts: ldap
  tasks:
    - name: Create User in LDAP
      ldap_entry:
        bind_dn: '{{ ldap_bind_dn }}'
        bind_pw: '{{ ldap_bind_password }}'
        dn: '{{ base_user_dn}}'
        server_uri: '{{ ldap_uri }}'
        # Support Self-Signed Certs
        validate_certs: no
        state: present
      tags:
        - ldap
