- hosts: hdp
  become: true
  tags:
    - os
  tasks:
    - name: Add Groups
      group:
        name: '{{ item }}'
        state: present
      loop:
        - flintstones
        - gameofthrones
        - starwars
        - hadoop_admin
        - service
    - name: Add Flintstones Users
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: hadoop, flintstones
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
    - name: Add gameofthrones Users
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: hadoop, gameofthrones
      loop:
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
    - name: Add Starwars Users
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: hadoop, starwars
      loop:
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
    - name: Add Service Group Membership
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: service
        append: yes
      loop:
        - coruscant
        - tatooine
        - bedrock
        - kingslanding
        - winterfell
