- hosts: sdlc
  vars:
    database: credit_card_01
    app_dir: apps/credit_card
    count: 5000

  tasks:
    - name: Check base dir exists
      file:
        path: "{{ ansible_env['HOME'] }}/{{ app_dir }}/generator"
        state: directory
        mode: 0755

    - name: Check dataset dir exists
      file:
        path: "{{ ansible_env['HOME'] }}/datasets/credit_card/acct"
        state: directory
        mode: 0755

    - name: Copy over the generator schema.
      copy:
        src: ../generator/cc-acct.yaml
        dest: "{{ ansible_env['HOME'] }}/{{ app_dir }}/generator/cc-acct.yaml"

    - name: Check base dir exists
      file:
        path: "{{ ansible_env['HOME'] }}/{{ app_dir }}/cdc"
        state: directory
        mode: 0755


    - name: Run the data generator, building {{ count }} records
      shell: datagen -cfg {{ ansible_env['HOME'] }}/{{ app_dir }}/generator/cc-acct.yaml -o {{ ansible_env['HOME'] }}/datasets/credit_card/acct/acct-{{ ansible_date_time.iso8601_basic_short }}.csv -c {{ count }}

    - name: Create target directory in HDFS
      shell: hdfs dfs -mkdir /warehouse/tablespace/external/hive/{{ database }}.db/CC_ACCT_DELTA_INGEST/processing_cycle={{ ansible_date_time.iso8601_basic_short }}

    - name: Copy generated file to hdfs
      shell: hdfs dfs -put {{ ansible_env['HOME'] }}/datasets/credit_card/acct/acct-{{ ansible_date_time.iso8601_basic_short }}.csv /warehouse/tablespace/external/hive/{{ database }}.db/CC_ACCT_DELTA_INGEST/processing_cycle={{ ansible_date_time.iso8601_basic_short }}

    - name: Sync table partitions with HDFS
      shell: hive -e "MSCK REPAIR TABLE {{ database }}.CC_ACCT_DELTA_INGEST SYNC PARTITIONS"

    - name: Copy over merge script for cc_acct.
      copy:
        src: ../cdc/cc-acct-merge.sql
        dest: "{{ ansible_env['HOME'] }}/{{ app_dir }}/cdc/cc-acct-merge.sql"

    - name: Merge Ingest Acct CDC with Account Table
      shell: hive --hivevar DATABASE={{ database }} --hivevar PROCESSING_CYCLE={{ ansible_date_time.iso8601_basic_short }} -f {{ ansible_env['HOME'] }}/{{ app_dir }}/cdc/cc-acct-merge.sql

    - name: Copy over append script for cc_acct_delta.
      copy:
        src: ../cdc/cc-acct-delta-append.sql
        dest: "{{ ansible_env['HOME'] }}/{{ app_dir }}/cdc/cc-acct-delta-append.sql"

    - name: Append Ingest Acct CDC with Account Delta Table
      shell: hive --hivevar DATABASE={{ database }} --hivevar PROCESSING_CYCLE={{ ansible_date_time.iso8601_basic_short }} -f {{ ansible_env['HOME'] }}/{{ app_dir }}/cdc/cc-acct-delta-append.sql