- hosts: sdlc
  vars:
    database: credit_card_01
    app_dir: apps/credit_card

  tasks:
    - name: Create base dir exists
      file:
        path: "{{ ansible_env['HOME'] }}/{{ app_dir }}/schema"
        state: directory
        mode: 0755

    - name: Copy over the schema ddl
      copy:
        src: ../schema/cc-schema.ddl
        dest: "{{ ansible_env['HOME'] }}/{{ app_dir }}/schema/cc-schema.ddl"
        force: yes

    - name: Run the schema file
      shell: hive --hivevar DATABASE={{ database }} -f {{ ansible_env['HOME'] }}/{{ app_dir }}/schema/cc-schema.ddl

    - name: Create base dir exists
      file:
        path: "{{ ansible_env['HOME'] }}/{{ app_dir }}/data"
        state: directory
        mode: 0755

    - name: Load State Base File
      copy:
        src: ../data/states.csv
        dest: "{{ ansible_env['HOME'] }}/{{ app_dir }}/data/states.csv"

    - name: Put the 'State' table in HDFS
      shell: hdfs dfs -put -f {{ ansible_env['HOME'] }}/{{ app_dir }}/data/states.csv /warehouse/tablespace/external/hive/{{ database }}.db/STATE