- hosts: sdlc
  vars:
    database: credit_card_01

  tasks:
    - name: Run external reset script
      shell: hive --hivevar DATABASE={{ database }} -e 'DROP DATABASE IF EXISTS {{ database }}_ext CASCADE'
