- hosts: sdlc
  vars:
    database: credit_card_01

  tasks:
    - name: Run managed reset script
      shell: hive --hivevar DATABASE={{ database }} -e 'DROP DATABASE IF EXISTS {{ database }} CASCADE'
