- hosts: sdlc
#  vars:
#    cc_trans_topic: '{{ cc_trans_topic }}'
#    cc_trans_topic_partitions: '{{ cc_trans_topic_partitions }}'
#    cc_trans_topic_replication_factor: '{{ cc_trans_topic_replication_factor }}'
#    kafka_bootstrap_servers: '{{ kafka_brokers }}'
#    kafka_bin_dir: '{{ kafka_broker_dir_bin }}'
#    zookeeper_quorum: '{{ zookeeper_quorum }}'

  tasks:
    - name: Dump all vars
      action: template src=dumpall.j2 dest=/tmp/ansible.all

    #    Create Kafka Topics for CSV and JSON versions
#    - name: Create Kafka Topic for JSON
#      shell: "{{ kafka_bin_dir }}/kafka-topics.sh --if-not-exists --create --topic {{ cc_trans_json_topic }} --partitions {{ cc_trans_json_topic_partitions }} --replication-factor {{ cc_trans_json_topic_replication_factor }} --zookeeper {{ zookeeper_quorom }}"
#      tags:
#      - json
#      - kafka
#      - setup

