- hosts: sdlc
  vars:
    cc_trans_topic: "CC_TRANS_JSON"
    cc_trans_topic_partitions: 20
    cc_trans_topic_replication_factor: 2
    kafka_bootstrap_servers: "os10.streever.local:6667"
    kafka_bin_dir: "/usr/hdp/current/kafka-broker/bin"
    zookeeper_quorom: "os04.streever.local:2181"

  tasks:
  #    Create Kafka Topics for CSV and JSON versions
    - name: Create Kafka Topic for JSON
      shell: "{{ kafka_bin_dir }}/kafka-topics.sh --if-not-exists --create --topic {{ cc_trans_json_topic }} --partitions {{ cc_trans_json_topic_partitions }} --replication-factor {{ cc_trans_json_topic_replication_factor }} --zookeeper {{ zookeeper_quorom }}"
      tags:
      - json
      - kafka
      - setup

