CREATE DATABASE IF NOT EXISTS ${DATABASE};

USE ${DATABASE};

DROP TABLE IF EXISTS COUNTY_CASES_SWEEP;

CREATE EXTERNAL TABLE IF NOT EXISTS COUNTY_CASES_SWEEP
(
    COUNTY_RESIDENT STRING,
    POSITIVE        BIGINT,
    DEATHS          BIGINT,
    HOSPITALIZATION BIGINT,
    CASE_RATE       DOUBLE
)
    ROW FORMAT DELIMITED
        FIELDS TERMINATED BY ','
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

-- Specifically NOT scripting DROP of Archive table to prevent
-- Accidental delete of data that can NOT be recovered.
DROP TABLE COUNTY_CASES_ARCHIVE;

CREATE TABLE IF NOT EXISTS COUNTY_CASES_ARCHIVE
(
    COUNTY_RESIDENT  STRING,
    POSITIVE         BIGINT,
    DEATHS           BIGINT,
    HOSPITALIZATION  BIGINT,
    CASE_RATE        DOUBLE,
    PROCESSING_CYCLE STRING
)
    PARTITIONED BY (
        YEAR_MONTH STRING
        );

DROP TABLE IF EXISTS COUNTY_CASES;

CREATE TABLE IF NOT EXISTS COUNTY_CASES
(
    COUNTY_RESIDENT STRING,
    POSITIVE        BIGINT,
    DEATHS          BIGINT,
    HOSPITALIZATION BIGINT,
    CASE_RATE       DOUBLE
);

DROP TABLE IF EXISTS DEATHS_SWEEP;

CREATE EXTERNAL TABLE IF NOT EXISTS DEATHS_SWEEP
(
    AGE               INT,
    RACE              STRING,
    SEX               STRING,
    COUNTY            STRING,
    CHRONIC_CONDITION STRING

)
    ROW FORMAT DELIMITED
        FIELDS TERMINATED BY ','
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE DEATHS_ARCHIVE;

CREATE TABLE IF NOT EXISTS DEATHS_ARCHIVE
(
    AGE               INT,
    RACE              STRING,
    SEX               STRING,
    COUNTY            STRING,
    CHRONIC_CONDITION STRING,
    PROCESSING_CYCLE  STRING

)
    PARTITIONED BY (
        YEAR_MONTH STRING
        );

DROP TABLE IF EXISTS DEATHS;

CREATE TABLE IF NOT EXISTS DEATHS
(
    AGE               INT,
    RACE              STRING,
    SEX               STRING,
    COUNTY            STRING,
    CHRONIC_CONDITION STRING

);

DROP TABLE IF EXISTS DEMOGRAPHICS_SWEEP;

CREATE EXTERNAL TABLE IF NOT EXISTS DEMOGRAPHICS_SWEEP
(
    ETHNICITY       STRING,
    RACE            STRING,
    CONFIRMED_CASES INT,
    DEATHS          INT

)
    ROW FORMAT DELIMITED
        FIELDS TERMINATED BY ','
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE DEMOGRAPHICS_ARCHIVE;

CREATE TABLE IF NOT EXISTS DEMOGRAPHICS_ARCHIVE
(
    ETHNICITY        STRING,
    RACE             STRING,
    CONFIRMED_CASES  INT,
    DEATHS           INT,
    PROCESSING_CYCLE STRING
)
    PARTITIONED BY (
        YEAR_MONTH STRING
        );

DROP TABLE IF EXISTS DEMOGRAPHICS;

CREATE TABLE IF NOT EXISTS DEMOGRAPHICS
(
    ETHNICITY       STRING,
    RACE            STRING,
    CONFIRMED_CASES INT,
    DEATHS          INT

);