CREATE DATABASE IF NOT EXISTS COVID_GA;

USE COVID_GA;

DROP TABLE IF EXISTS COUNTY_CASES;

CREATE EXTERNAL TABLE IF NOT EXISTS COUNTY_CASES
(
    COUNTY_RESIDENT STRING,
    POSITIVE        BIGINT,
    DEATHS          BIGINT,
    HOSPITALIZATION BIGINT,
    CASE_RATE       DOUBLE
)
    ROW FORMAT DELIMITED
        FIELDS TERMINATED BY ','
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS DEATHS;

CREATE EXTERNAL TABLE IF NOT EXISTS DEATHS
(
    AGE               INT,
    RACE              STRING,
    SEX               STRING,
    COUNTY            STRING,
    CHRONIC_CONDITION STRING

)
    ROW FORMAT DELIMITED
        FIELDS TERMINATED BY ','
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS DEMOGRAPHICS;

CREATE EXTERNAL TABLE IF NOT EXISTS DEMOGRAPHICS
(
    ETHNICITY       STRING,
    RACE            STRING,
    CONFIRMED_CASES INT,
    DEATHS          INT

) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ','
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");
