CREATE DATABASE IF NOT EXISTS COVID_GITHUB;

USE COVID_GITHUB;

DROP TABLE IF EXISTS IN_COUNTRIES_AGGREGATED;

CREATE EXTERNAL TABLE IF NOT EXISTS IN_COUNTRIES_AGGREGATED
(
    RECORD_DATE DATE COMMENT "DATE",
    COUNTRY     STRING COMMENT "Country",
    CONFIRMED   BIGINT COMMENT "Confirmed",
    RECOVERED   BIGINT COMMENT "Recovered",
    DEATHS      BIGINT COMMENT "Deaths"
)
    ROW FORMAT SERDE
        'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS IN_KEY_COUNTRIES_PIVOTED;

CREATE EXTERNAL TABLE IF NOT EXISTS IN_KEY_COUNTRIES_PIVOTED
(
    RECORD_DATE DATE COMMENT "Date",
    CHINA       BIGINT COMMENT "China",
    US          BIGINT COMMENT "US",
    UK          BIGINT COMMENT "United Kingdom",
    ITALY       BIGINT COMMENT "Italy",
    FRANCE      BIGINT COMMENT "FRANCE",
    GERMANY     BIGINT COMMENT "Germany",
    SPAIN       BIGINT COMMENT "SPAIN",
    IRAN        BIGINT COMMENT "IRAN"
)
    ROW FORMAT SERDE
        'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS IN_REFERENCE;

CREATE EXTERNAL TABLE IN_REFERENCE (
    UID STRING,
    ISO2 STRING,
    ISO3 STRING,
    CODE STRING,
    FIPS STRING,
    ADMIN2 STRING,
    PROVINCE_STATE STRING,
    COUNTRY_REGION STRING,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    COMBINED_KEY STRING,
    POPULATION BIGINT
)
    ROW FORMAT SERDE
        'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS IN_TIME_SERIES_COMBINED;

CREATE EXTERNAL TABLE IF NOT EXISTS IN_TIME_SERIES_COMBINED (
    RECORD_DATE DATE,
    COUNTRY_REGION STRING,
    STATE STRING,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    CONFIRMED BIGINT,
    RECOVERED BIGINT,
    DEATHS BIGINT
)ROW FORMAT SERDE
    'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS IN_US_CONFIRMED;

CREATE EXTERNAL TABLE IF NOT EXISTS IN_US_CONFIRMED (
    UID STRING,
    ISO2 STRING,
    ISO3 STRING,
    CODE3 STRING,
    FIPS STRING,
    ADMIN2 STRING,
    LATITUDE DOUBLE,
    COMBINED_KEY STRING,
    RECORD_DATE DATE,
    CASES BIGINT,
    LONGITUDE BIGINT,
    COUNTRY STRING,
    STATE STRING
)
    ROW FORMAT SERDE
        'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS IN_US_DEATHS;

CREATE EXTERNAL TABLE IF NOT EXISTS IN_US_DEATHS (
    UID STRING,
    ISO2 STRING,
    ISO3 STRING,
    CODE3 STRING,
    FIPS STRING,
    ADMIN2 STRING,
    LATITUDE DOUBLE,
    COMBINED_KEY STRING,
    POPULATION BIGINT,
    RECORD_DATE DATE,
    CASES BIGINT,
    LONGITUDE DOUBLE,
    COUNTRY STRING,
    STATE STRING
)
    ROW FORMAT SERDE
        'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");

DROP TABLE IF EXISTS IN_WORLDWIDE_AGGREGATED;

CREATE EXTERNAL TABLE IN_WORLDWIDE_AGGREGATED (
    RECORD_DATE DATE,
    CONFIRMED BIGINT,
    RECOVERED BIGINT,
    DEATHS BIGINT,
    INCREASE_RATE DOUBLE
)
    ROW FORMAT SERDE
        'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    STORED AS TEXTFILE
    TBLPROPERTIES ("skip.header.line.count" = "1");