USE COVID_GITHUB;

SELECT * FROM IN_COUNTRIES_AGGREGATED LIMIT 10;

SELECT * FROM IN_KEY_COUNTRIES_PIVOTED LIMIT 10;

SELECT * FROM IN_REFERENCE LIMIT 10;

SELECT * FROM IN_TIME_SERIES_COMBINED LIMIT 10;

SELECT * FROM IN_US_CONFIRMED LIMIT 10;

SELECT * FROM IN_US_DEATHS LIMIT 10;

SELECT * FROM IN_WORLDWIDE_AGGREGATED LIMIT 10;
