CREATE DATABASE IF NOT EXISTS COVID_GITHUB;

USE COVID_GITHUB;

DROP TABLE IF EXISTS COUNTRIES_AGGREGATED;

CREATE TABLE IF NOT EXISTS COUNTRIES_AGGREGATED AS
    SELECT * FROM IN_COUNTRIES_AGGREGATED;

DROP TABLE IF EXISTS KEY_COUNTRIES_PIVOTED;

CREATE TABLE IF NOT EXISTS KEY_COUNTRIES_PIVOTED AS SELECT * FROM IN_KEY_COUNTRIES_PIVOTED;

DROP TABLE IF EXISTS REFERENCE;

CREATE TABLE IF NOT EXISTS REFERENCE AS  SELECT * FROM IN_REFERENCE;

DROP TABLE IF EXISTS TIME_SERIES_COMBINED;

CREATE  TABLE IF NOT EXISTS TIME_SERIES_COMBINED AS SELECT * FROM IN_TIME_SERIES_COMBINED;

DROP TABLE IF EXISTS US_CONFIRMED;

CREATE  TABLE IF NOT EXISTS US_CONFIRMED AS SELECT * FROM IN_US_CONFIRMED;

DROP TABLE IF EXISTS US_DEATHS;

CREATE TABLE IF NOT EXISTS US_DEATHS AS SELECT * FROM IN_US_DEATHS;

DROP TABLE IF EXISTS WORLDWIDE_AGGREGATE;

CREATE TABLE IF NOT EXISTS WORLDWIDE_AGGREGATED AS SELECT * FROM IN_WORLDWIDE_AGGREGATED;