
USE COVID_KAGGLE;
SHOW TABLES;

SELECT * FROM COUNTRY_WISE_LATEST LIMIT 10;

SELECT * FROM CLEAN_COMPLETE LIMIT 10;

SELECT * FROM DAY_WISE LIMIT 10;

SELECT * FROM FULL_GROUPED LIMIT 10;

SELECT * FROM USA_COUNTY_WISE LIMIT 10;

SELECT * FROM WORLDOMETER_DATA WHERE RECORD_DATE = '2020-08-05' LIMIT 10;

